---
title: "Racial Disparities and Trends in Endometrial Cancer from 2000-2021"
author: Arnetta McVey Moffatt
output: github_document
---

### Report Overview

This repository contains the data and code needed to render a report on Endometrial Cancer trends in SEER data. This analysis uses data from the SEER\*Stat Database: Incidence - SEER Research Plus Data, 17 Registries, Nov 2023 Sub (2000-2021). Non-Hispanic Black and Non-Hispanic White women were included if they were diagnosed between 2000 and 2021 with invasive EC.

The report includes Tables 1-3 and Figure 1 which identify population and biological characteristic of the study population, analysis of endometrial cancer death by selected characteristic and trends in endometrial cancer between 2000 and 2021.

To render the report after downloading the repository, either the Makefile should be used to generate the figures and final report or each individual section of code should be run in numerical order (1 through 5).

#### Repository Organization

-   Code directory: Contains all R script files required for the analysis in the final report
-   Data directory: Stores the data set used in the report
-   Output directory: Holds all intermediate data generated during the analysis
-   Makefile: Automates the analysis workflow and output generation
    -   When Make is installed, running the command Make in the terminal will generate the final report and running the command Make clean will reset the repository after generating the report
